sudo: false

language: java

jdk:
  - openjdk8

script: 
  - chmod 700 ./mvnw
  - ./mvnw clean install
  - cd test
  - ../mvnw clean test
  
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  
after_success:
  - cd ..
  - python addsettings.py
  - cd bsoncodec-apt
  - mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml

cache:
  directories:
  - $HOME/.m2