sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java

jdk:
  - oraclejdk8

script: 
  - chmod 700 ./mvnw
  - ./mvnw clean install
  - cd test
  - ../mvnw clean test
  
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  - secure: t7/fSzRn+H4VjbmYrL0N5CqYcynwR6r95STDf57ZfiCT1QaAPMTpVMpu1tuOaEFzSpL2xBcqtxeBpoA3Lq7ViDVL5vv1jKs581uzDdr0OcxSiFUHQkn43N0+ab8wvT2VQpTZ3wVypOYyUHiA46I0gQk2HvplWcDR3r1ix0izZwMFEHl93CqS30EP0bS/NXLY6mOINP0cCy1uqB3dy8uekuFUdPBlJ4tz45h7P1M26VRGtKC2iK0+tzeGZU+dNbwE5FCTX//37eh31XnTruYkDEvQOtCV6eEposUlFdgpGs4KqNz1j5iWZ5SzZa7LaIEWBRsvXsMWqmW69w0kM/dLDorqQ/bVZQr3yPpLlWq+llLIcz9l6JWVjXbYC5fboNmyDQpJNPJek/mCURfkwT8QJraKysIg+/U5FzMyNqOot28gvg7hsviIPAKJhvqRtoN0/mdgI8pNv2+6DKqD2MLUkFRRWCapfrRqiLUVpipzE9rFQPDgiRK1trv+U0/p1NYgISYPDKSLLE3a96qYo1CwWnlm7PbJ4Sk4EWtG9mH+df2/HOX+8ys2gtASt9UHlegsJHifE7BrrVs/rVizveg4GDEp207fLnCostEc52yVjQoFr7vR9+XPnL7wUWeMtByb9dvrGM8+I3V3JWxt3XgYsU90t/9zLoskCMl1jDILz94=
  
after_success:
  - cd ..
  - python addsettings.py
  - cd bsoncodec-apt
  - mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml

cache:
  directories:
  - $HOME/.m2